version: 3

vars:
  CWD:
    sh: pwd
  VERSION:
    sh: pulumictl get version

tasks:
  schemagen:
    cmds:
      - go build -o ../bin/pulumi-gen-awsx ./cmd/pulumi-gen-awsx
    dir: schemagen
    sources:
      - "**/*"
    
  schema:
    cmds:
      - bin/pulumi-gen-awsx schema awsx
    deps:
      - schemagen
    sources:
      - bin/pulumi-gen-awsx
